#!/bin/sh
if [ "$1" = "remove" ]; then
	plugin_dir="/data/ubuntu/root/plugins/streamingserver"
	for adir in xhamster xnxx xvideos; do
		if [ -d $plugin_dir/providers/$adir ]; then
			rm -rf $plugin_dir/providers/$adir
		fi
	done

	rm -rf /usr/lib/enigma2/python/Plugins/SystemPlugins/Area-51
	echo "Plugin removed successfully."
else
	echo "Do nothing..."
fi
exit 0
